#DB properties
spring:
    application:
        name: webclient        
    # datasource:
    #     driver: com.mysql.cj.jdbc.Driver
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    #     password: 1999
    #     url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
    #     username: demouser
    devtools:
        restart:
            enabled: true
            poll-interval: 2s
            quiet-period: 1s
    mustache:
        expose-request-attributes: true
        suffix: '.html' 
 
    jpa:
        hibernate:
            ddl-auto: create-drop # create : 생성후 유지
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            show-sql: true 
    h2:
        console:
            enabled: true
            path: /h2_db
    datasource:
        url: jdbc:h2:file:~/EMDB/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        driver-class-name: org.h2.Driver
        username: yoon
        password: 1234


server:
  port: ${service_port:5013}

  



